name: go-test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  go-test:
    name: go-test
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      BLOCKFROST_KEY: ${{ secrets.BLOCKFROST_KEY }}
      DMTR_API_KEY: ${{ secrets.DMTR_API_KEY }}
      OGMIOS_ENDPOINT: ${{ secrets.OGMIOS_ENDPOINT }}
      KUPO_ENDPOINT: ${{ secrets.KUPO_ENDPOINT }}
      UTXORPC_URL: ${{ secrets.UTXORPC_URL }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: go-test
        run: go test ./...
